### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by pjvilloud** [voxars/JavaAudiotheque#1]
cf https://github.com/Jakyln/IPI-JavaWebAudiotheque/issues/1

**Comment by voxars** [comment]
Bonjour monsieur, 
Tout d'abord merci pour la correction mais pour ce projet, je me suis tourné vers Julien pour de l'aide sur quelques points du tp mais nous ne l'avons pas réaliser ensemble. Il a d'ailleurs normalement finaliser le projet avant moi. Je tiens a m'excuser si nos projets se ressemble et si cela vous a fait perdre du temps.
Cordialement
